version: '3'

services:
  app:
    build: .
    container_name: api
    restart: on-failure
    ports:
      - '8000:8000'
    environment:
      DATABASE_HOST: 'db'
    env_file:
      - '.env-app'
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    restart: on-failure
    container_name: postgres
    env_file:
      - '.env-postgresql'
