[tool.poetry]
name = "clean-architecture-fastapi"
version = "0.1.0"
description = "api server with clean architecture"
authors = ["Suzuki Masaya <vagrant@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.63.0"
SQLAlchemy = "^1.3.22"
uvicorn = "^0.13.2"
email-validator = "^1.1.2"
psycopg2 = "^2.8.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
mypy = "^0.790"
flake8 = "^3.8.4"
black = "^20.8b1"
requests = "^2.25.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
